services:
  - type: web
    name: nxcar-ultra
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1
    envVars:
      - key: DATA_DIR
        value: /tmp/nxcar
      - key: PYTHON_VERSION
        value: 3.11.0
